"""Conga PR Porter — TRX parser and PR body generator.

JIRA operations are handled by the JIRA MCP server (configured in mcp.json).
GitHub operations use `gh` CLI directly.
This script handles only: TRX test result parsing and PR body markdown generation.

Usage:
    python pr_porter.py generate-pr-body --original-pr 123 --original-repo congaengr/Repo --target-branch release/2025.1 --jira-ticket REVREN-456
    python pr_porter.py parse-trx --file ./TestResults/port-test-results.trx

Requires: Python 3.10+ (stdlib only, zero dependencies).
"""

import argparse
import sys
from pathlib import Path

# Import shared utilities
sys.path.insert(0, str(Path(__file__).parent.parent))
from conga_common import parse_trx, format_test_results_table, write_markdown, timestamp

SCRIPT_DIR = Path(__file__).resolve().parent


# ============================================================================
# TRX Parser (CLI wrapper with console output)
# ============================================================================

def cmd_parse_trx(trx_path):
    """Parse a .trx test results file and print summary to console."""
    result = parse_trx(trx_path)
    if not result:
        print(f"ERROR: TRX file not found: {trx_path}")
        return None

    print(f"Test Results: {result['passed']}/{result['total']} passed, "
          f"{result['failed']} failed, {result['skipped']} skipped")
    
    if result["failed_tests"]:
        print("\nFailed tests:")
        for ft in result["failed_tests"]:
            print(f"  - {ft['name']}: {ft['error'][:100]}")

    return result


# ============================================================================
# PR Body Generator
# ============================================================================

def generate_pr_body(original_pr, original_repo, target_branch, jira_ticket,
                     test_results_path=None, commits=None, jira_base_url="https://congacloud.atlassian.net"):
    """Generate markdown PR body and write to pr-body.md."""
    lines = [
        f"## Port: Changes from PR #{original_pr}",
        "",
        f"**JIRA:** [{jira_ticket}]({jira_base_url}/browse/{jira_ticket})",
        f"**Original PR:** [{original_repo}#{original_pr}](https://github.com/{original_repo}/pull/{original_pr})",
        f"**Ported to:** `{target_branch}`",
        f"**Ported on:** {timestamp()}",
        "",
    ]

    if commits:
        lines.append("### Commits Ported")
        for c in commits.split(","):
            c = c.strip()
            if c:
                lines.append(f"- `{c[:12]}`")
        lines.append("")

    test_summary = parse_trx(test_results_path) if test_results_path else None

    if test_summary:
        lines.extend([
            "### Test Results",
            "",
            format_test_results_table(test_summary),
            ""
        ])
    else:
        lines.extend(["### Test Results", "", "_Test results not available._", ""])

    lines.extend(["---", "_Generated by Conga PR Porter skill_"])

    body = "\n".join(lines)
    out_path = write_markdown(body, SCRIPT_DIR / "pr-body.md")
    print(f"PR body written to: {out_path}")
    return body


# ============================================================================
# CLI
# ============================================================================

def main():
    parser = argparse.ArgumentParser(description="PR Porter — TRX parsing and PR body generation")
    sub = parser.add_subparsers(dest="command")

    gp = sub.add_parser("generate-pr-body", help="Generate PR body markdown")
    gp.add_argument("--original-pr", required=True)
    gp.add_argument("--original-repo", required=True)
    gp.add_argument("--target-branch", required=True)
    gp.add_argument("--jira-ticket", required=True)
    gp.add_argument("--test-results", help="Path to .trx file")
    gp.add_argument("--commits", help="Comma-separated commit SHAs")
    gp.add_argument("--jira-base-url", default="https://congacloud.atlassian.net")

    pt = sub.add_parser("parse-trx", help="Parse .trx test results")
    pt.add_argument("--file", required=True)

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "generate-pr-body":
        generate_pr_body(args.original_pr, args.original_repo, args.target_branch,
                         args.jira_ticket, args.test_results, args.commits, args.jira_base_url)
    elif args.command == "parse-trx":
        if not cmd_parse_trx(args.file):
            sys.exit(1)


if __name__ == "__main__":
    main()